version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: timotimo
      POSTGRES_PASSWORD: timotimo
      POSTGRES_DB: banking
    ports:
      - "5433:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U timotimo"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
